[package]
name = "distributor"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "22.0.7"
soroban-env-common = "22.0.7"
soroban-env-macros = "22.0.7"

[dev-dependencies]
soroban-sdk-macros = "22.0.7"